import { useEffect, useState } from "react";
import Head from "next/head";
import FloatNavbar from "../components/FloatNavbar";
import Hero from "../components/Hero";
import Navbar from "../components/Navbar";
import { About } from "../components/About";
import { Education } from "../components/Education";
import { Skills } from "../components/Skills";
import { Experience } from "../components/Experience";
import { Projects } from "../components/Projects";
import { Contact } from "../components/Contact";
import ScrollButton from "../components/ScrollButton";

export default function Home() {
  const [isChange, setIsChange] = useState(false);
  const [dark, setDark] = useState(false);
  useEffect(() => {
    window.addEventListener("scroll", handleScroll);
    return () => window.removeEventListener("scroll", handleScroll);
  });
  const handleScroll = () => {
    if (window.scrollY > 0) {
      setIsChange(true);
    } else {
      setIsChange(false);
    }
  };
  return (
    <div className={dark?"dark":""}>
      <Head>
        <title>Aditya Kumar</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/adi.ico" />
      </Head>

      <main>
        <section
          className={`sticky top-0 px-6 md:px-8 lg:px-10 z-10 w-[100%] ${
            isChange ? " bg-[#fcfcfc] shadow-md" : ""
          }`}
        >
          <Navbar setDark={setDark} dark={dark} />
        </section>
        <section className="min-h-screen px-10" id="#">
          <Hero />
        </section>
        <section className="min-h-screen px-10" id="about">
          <About />
        </section>
        <section className="min-h-screen px-10" id="education">
          <Education />
        </section>
        <section className="min-h-screen px-10" id="skills">
          <Skills />
        </section>
        <section className="min-h-screen px-10" id="experience">
          <Experience />
        </section>
        <section className="min-h-screen px-10" id="projects">
          <Projects />
        </section>
        <section className="min-h-screen px-10" id="contact">
          <Contact />
        </section>
        <FloatNavbar />
        <ScrollButton />
      </main>
    </div>
  );
}
